name: Publish Docker Image

on:
    workflow_call:
        inputs:
            image_name:
                required: true
                type    : string
            tag:
                type    : string
        secrets:
            registry_username:
                required: true
            registry_password:
                required: true                

jobs: 
    build:
        #name: some-name
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.1

            - name: Setup buildx
              uses: docker/setup-buildx-action@v3.3.0

            - name: Login to the Registry
              uses: docker/login-action@v3.1.0
              with:
                username: ${{ secrets.DOCKER_HUB_UNAME}}
                password: ${{ secrets.DOCKER_HUB_PSW }}

            - name: Set the tag
              run: |
                if [ -z "${{ inputs.tag" }} ]
                then
                    echo "tag_value=latest" >> $GITHUB_ENV
                else
                    echo "tag_value=${{ inputs.tag }}" >> $GITHUB_ENV    
                fi
                
            - name: Build and push the image
              uses: docker/build-push-action@v5.3.0
              with:
                context: .
                push   : true
                tags   : ${{secrets.DOCKER_HUB_UNAME}}/${{inputs.image_name}}:${{env.tag_value}}

    second-job:
        runs-on: ubuntu-latest
        
        steps:
            - name: Print message
              run : echo "Hello from second-job"
